import { PDFDocument, rgb, StandardFonts, type PDFFont, type PDFPage } from "pdf-lib";
import { formatMYR, type InvoiceLineItem } from "@/lib/invoices";

export interface InvoicePdfData {
  kind: "INVOICE" | "RECEIPT";
  invoiceNumber: string;
  issuedAt: Date;
  dueDate: Date | null;
  paidAt: Date | null;
  statusLabel: string;
  clinic: { name: string; lines: string[] };
  patient: { name: string; lines: string[] };
  items: InvoiceLineItem[];
  total: number;
  notes: string | null;
}

const INK = rgb(0.04, 0.15, 0.25);
const MUTED = rgb(0.41, 0.45, 0.53);
const RULE = rgb(0.89, 0.91, 0.93);
const BRAND = rgb(0.39, 0.36, 1);

const dateMY = (d: Date) =>
  d.toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Kuala_Lumpur" });

/** Standard fonts are WinAnsi-only; drop anything they can't draw rather than failing the whole PDF. */
const safe = (text: string) => text.replace(/[^\x20-\x7E -ÿ]/g, "?");

function text(page: PDFPage, value: string, x: number, y: number, font: PDFFont, size = 10, color = INK) {
  page.drawText(safe(value), { x, y, size, font, color });
}

function rightText(page: PDFPage, value: string, right: number, y: number, font: PDFFont, size = 10, color = INK) {
  const v = safe(value);
  page.drawText(v, { x: right - font.widthOfTextAtSize(v, size), y, size, font, color });
}

/** A4 invoice (or receipt, once paid) with the clinic, patient, line items and total. */
export async function renderInvoicePdf(data: InvoicePdfData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${data.kind === "RECEIPT" ? "Receipt" : "Invoice"} ${data.invoiceNumber}`);
  const page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const left = 48;
  const right = 547;
  let y = 790;

  text(page, data.clinic.name, left, y, bold, 16);
  rightText(page, data.kind, right, y, bold, 20, BRAND);
  y -= 18;
  for (const line of data.clinic.lines) {
    text(page, line, left, y, font, 9, MUTED);
    y -= 12;
  }

  let metaY = 766;
  const meta: [string, string][] = [
    [data.kind === "RECEIPT" ? "Receipt for" : "Invoice no.", data.invoiceNumber],
    ["Issued", dateMY(data.issuedAt)],
    ...(data.dueDate && data.kind === "INVOICE" ? [["Due", dateMY(data.dueDate)] as [string, string]] : []),
    ...(data.paidAt ? [["Paid", dateMY(data.paidAt)] as [string, string]] : []),
    ["Status", data.statusLabel],
  ];
  for (const [label, value] of meta) {
    rightText(page, `${label}: ${value}`, right, metaY, font, 9, MUTED);
    metaY -= 12;
  }

  y = Math.min(y, metaY) - 24;
  text(page, "BILL TO", left, y, bold, 8, MUTED);
  y -= 14;
  text(page, data.patient.name, left, y, bold, 11);
  y -= 13;
  for (const line of data.patient.lines) {
    text(page, line, left, y, font, 9, MUTED);
    y -= 12;
  }

  y -= 20;
  const cols = { qty: 380, unit: 460, total: right };
  text(page, "Description", left, y, bold, 9, MUTED);
  rightText(page, "Qty", cols.qty, y, bold, 9, MUTED);
  rightText(page, "Unit price", cols.unit, y, bold, 9, MUTED);
  rightText(page, "Amount", cols.total, y, bold, 9, MUTED);
  y -= 6;
  page.drawLine({ start: { x: left, y }, end: { x: right, y }, thickness: 0.6, color: RULE });
  y -= 16;
  for (const item of data.items) {
    if (y < 120) break;
    text(page, item.description.slice(0, 60), left, y, font, 10);
    rightText(page, String(item.quantity), cols.qty, y, font, 10);
    rightText(page, formatMYR(item.unitPrice), cols.unit, y, font, 10);
    rightText(page, formatMYR(item.total), cols.total, y, font, 10);
    y -= 18;
  }
  page.drawLine({ start: { x: 330, y: y + 6 }, end: { x: right, y: y + 6 }, thickness: 0.6, color: RULE });
  y -= 10;
  text(page, data.kind === "RECEIPT" ? "Amount paid" : "Total due", 330, y, bold, 11);
  rightText(page, formatMYR(data.total), right, y, bold, 12);

  if (data.notes) {
    y -= 36;
    text(page, "Notes", left, y, bold, 9, MUTED);
    y -= 13;
    text(page, data.notes.slice(0, 110), left, y, font, 9);
  }

  text(page, "Thank you. Generated by SmartChiro.", left, 40, font, 8, MUTED);
  return pdf.save();
}
