import { PrismaClient } from '@prisma/client'
import { PrismaNeon } from '@prisma/adapter-neon'
import { hash } from 'bcryptjs'
import 'dotenv/config'

const connectionString = process.env.DATABASE_URL!

const adapter = new PrismaNeon({ connectionString })
const prisma = new PrismaClient({ adapter })

async function main() {
  const hashedPassword = await hash('12345678', 12)

  // ─── Demo Owner (existing) ───
  const owner = await prisma.user.upsert({
    where: { email: 'demo@smartchiro.org' },
    update: {},
    create: {
      email: 'demo@smartchiro.org',
      name: 'Demo Wojak',
      password: hashedPassword,
      isPro: false,
      emailVerified: new Date(),
    },
  })
  console.log(`Seeded owner: ${owner.email} (id: ${owner.id})`)

  // ─── Branch ───
  const branch = await prisma.branch.upsert({
    where: { id: 'demo-branch-001' },
    update: {},
    create: {
      id: 'demo-branch-001',
      name: 'SmartChiro Demo Branch',
      address: '123 Main Street',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      zip: '50000',
      phone: '+60 12-345 6789',
      email: 'branch@smartchiro.org',
      ownerName: 'Demo Wojak',
      clinicType: 'group',
      operatingHours: 'Mon-Fri 9am-6pm, Sat 9am-1pm',
      treatmentRooms: 4,
      specialties: 'Gonstead, Diversified, Sports Chiropractic',
      insuranceProviders: 'AIA, Great Eastern, Prudential',
    },
  })
  console.log(`Seeded branch: ${branch.name}`)

  // Link owner to branch
  await prisma.branchMember.upsert({
    where: { userId_branchId: { userId: owner.id, branchId: branch.id } },
    update: { role: 'OWNER' },
    create: { userId: owner.id, branchId: branch.id, role: 'OWNER' },
  })
  await prisma.user.update({
    where: { id: owner.id },
    data: { activeBranchId: branch.id },
  })
  console.log(`Linked owner → branch`)

  // ─── Doctors ───
  const doctorsData = [
    {
      email: 'dr.lim@smartchiro.org',
      name: 'Dr. Lim Wei Jie',
      phone: '+60 12-888 1234',
      role: 'ADMIN' as const,
      profile: {
        licenseNumber: 'DC-MY-2018-4521',
        specialties: ['Gonstead Technique', 'Sports Chiropractic', 'Pediatric Chiropractic'],
        yearsExperience: 8,
        education: 'Doctor of Chiropractic, RMIT University Melbourne',
        bio: 'Specializes in Gonstead technique with a focus on sports injuries and pediatric care. Former team chiropractor for Selangor FC.',
        languages: ['English', 'Mandarin', 'Malay'],
        insurancePlans: ['AIA', 'Great Eastern', 'Prudential'],
        consultationFee: 150,
        treatmentRoom: 'Room A',
        workingSchedule: {
          monday: { start: '09:00', end: '18:00' },
          tuesday: { start: '09:00', end: '18:00' },
          wednesday: { start: '09:00', end: '18:00' },
          thursday: { start: '09:00', end: '18:00' },
          friday: { start: '09:00', end: '17:00' },
          saturday: { start: '09:00', end: '13:00' },
        },
      },
    },
    {
      email: 'dr.aisha@smartchiro.org',
      name: 'Dr. Aisha binti Razak',
      phone: '+60 17-555 9876',
      role: 'DOCTOR' as const,
      profile: {
        licenseNumber: 'DC-MY-2020-6103',
        specialties: ['Diversified Technique', 'Prenatal Chiropractic', 'Rehabilitation'],
        yearsExperience: 5,
        education: 'Doctor of Chiropractic, International Medical University (IMU)',
        bio: 'Passionate about prenatal and postpartum chiropractic care. Certified in Webster Technique for pregnancy-related adjustments.',
        languages: ['English', 'Malay', 'Arabic'],
        insurancePlans: ['AIA', 'Allianz'],
        consultationFee: 130,
        treatmentRoom: 'Room B',
        workingSchedule: {
          monday: { start: '10:00', end: '18:00' },
          tuesday: { start: '10:00', end: '18:00' },
          wednesday: null,
          thursday: { start: '10:00', end: '18:00' },
          friday: { start: '10:00', end: '17:00' },
          saturday: { start: '09:00', end: '13:00' },
        },
      },
    },
    {
      email: 'dr.kumar@smartchiro.org',
      name: 'Dr. Rajesh Kumar',
      phone: '+60 16-333 4567',
      role: 'DOCTOR' as const,
      profile: {
        licenseNumber: 'DC-MY-2015-2890',
        specialties: ['Thompson Technique', 'Activator Method', 'Geriatric Chiropractic'],
        yearsExperience: 11,
        education: 'Doctor of Chiropractic, Murdoch University Perth',
        bio: 'Senior chiropractor specializing in gentle techniques suitable for elderly patients. Published researcher in spinal degeneration management.',
        languages: ['English', 'Tamil', 'Malay'],
        insurancePlans: ['Great Eastern', 'Prudential', 'AXA'],
        consultationFee: 180,
        treatmentRoom: 'Room C',
        workingSchedule: {
          monday: { start: '08:00', end: '16:00' },
          tuesday: { start: '08:00', end: '16:00' },
          wednesday: { start: '08:00', end: '16:00' },
          thursday: { start: '08:00', end: '16:00' },
          friday: { start: '08:00', end: '14:00' },
          saturday: null,
        },
      },
    },
  ]

  const doctorUsers: { id: string; name: string }[] = []

  for (const d of doctorsData) {
    const user = await prisma.user.upsert({
      where: { email: d.email },
      update: {},
      create: {
        email: d.email,
        name: d.name,
        password: hashedPassword,
        phoneNumber: d.phone,
        emailVerified: new Date(),
        activeBranchId: branch.id,
      },
    })

    await prisma.branchMember.upsert({
      where: { userId_branchId: { userId: user.id, branchId: branch.id } },
      update: { role: d.role },
      create: { userId: user.id, branchId: branch.id, role: d.role },
    })

    await prisma.doctorProfile.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        licenseNumber: d.profile.licenseNumber,
        specialties: d.profile.specialties,
        yearsExperience: d.profile.yearsExperience,
        education: d.profile.education,
        bio: d.profile.bio,
        languages: d.profile.languages,
        insurancePlans: d.profile.insurancePlans,
        consultationFee: d.profile.consultationFee,
        treatmentRoom: d.profile.treatmentRoom,
        workingSchedule: d.profile.workingSchedule,
        isActive: true,
      },
    })

    doctorUsers.push({ id: user.id, name: d.name })
    console.log(`Seeded doctor: ${d.name} (${d.role})`)
  }

  // Also add owner to the doctor pool for patient assignment
  const allDoctors = [{ id: owner.id, name: owner.name ?? 'Demo Wojak' }, ...doctorUsers]

  // ─── Patients ───
  const patientsData = [
    {
      firstName: 'Ahmad',
      lastName: 'bin Ibrahim',
      email: 'ahmad.ibrahim@gmail.com',
      phone: '+60 11-1111 2001',
      icNumber: '850315-14-5523',
      dateOfBirth: new Date('1985-03-15'),
      gender: 'Male',
      occupation: 'Software Engineer',
      race: 'Malay',
      maritalStatus: 'Married',
      bloodType: 'O+',
      allergies: 'Penicillin',
      referralSource: 'Google Search',
      addressLine1: '12, Jalan Bukit Bintang',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '55100',
      emergencyName: 'Siti Aminah',
      emergencyPhone: '+60 12-999 0001',
      emergencyRelation: 'Wife',
      medicalHistory: 'Lower back pain for 3 years. Previous physiotherapy with limited improvement. Desk job, sitting 8+ hours daily.',
      notes: 'Prefers morning appointments. Responds well to Gonstead adjustments.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Tan',
      lastName: 'Mei Ling',
      email: 'meilingtan@yahoo.com',
      phone: '+60 11-1111 2002',
      icNumber: '920728-10-6644',
      dateOfBirth: new Date('1992-07-28'),
      gender: 'Female',
      occupation: 'Accountant',
      race: 'Chinese',
      maritalStatus: 'Single',
      bloodType: 'A+',
      allergies: null,
      referralSource: 'Friend recommendation',
      addressLine1: '45, Jalan SS2/72',
      addressLine2: 'Taman SEA',
      city: 'Petaling Jaya',
      state: 'Selangor',
      postcode: '47300',
      emergencyName: 'Tan Wei Ming',
      emergencyPhone: '+60 12-999 0002',
      emergencyRelation: 'Father',
      medicalHistory: 'Neck pain and headaches. Frequent computer usage at work.',
      notes: 'First-time chiropractic patient. Slightly anxious about adjustments.',
      status: 'active',
      doctorIndex: 1,
    },
    {
      firstName: 'Priya',
      lastName: 'Nair',
      email: 'priya.nair@hotmail.com',
      phone: '+60 11-1111 2003',
      icNumber: '780912-08-4412',
      dateOfBirth: new Date('1978-09-12'),
      gender: 'Female',
      occupation: 'Teacher',
      race: 'Indian',
      maritalStatus: 'Married',
      bloodType: 'B+',
      allergies: 'Latex',
      referralSource: 'Dr. Kumar referral',
      addressLine1: '8, Lorong Maarof',
      city: 'Bangsar',
      state: 'Wilayah Persekutuan',
      postcode: '59000',
      emergencyName: 'Ravi Nair',
      emergencyPhone: '+60 12-999 0003',
      emergencyRelation: 'Husband',
      medicalHistory: 'Chronic thoracic pain. History of scoliosis diagnosed at age 14. Regular maintenance care.',
      notes: 'Long-term patient. Comes every 2 weeks for maintenance adjustments.',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Mohd',
      lastName: 'Faizal',
      email: 'faizal.mohd@gmail.com',
      phone: '+60 11-1111 2004',
      icNumber: '900405-01-5567',
      dateOfBirth: new Date('1990-04-05'),
      gender: 'Male',
      occupation: 'Personal Trainer',
      race: 'Malay',
      maritalStatus: 'Single',
      bloodType: 'AB+',
      allergies: null,
      referralSource: 'Instagram',
      addressLine1: '22, Jalan Ampang',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50450',
      emergencyName: 'Fatimah binti Hassan',
      emergencyPhone: '+60 12-999 0004',
      emergencyRelation: 'Mother',
      medicalHistory: 'Sports injury — rotator cuff strain. Herniated disc L4-L5 from deadlifting.',
      notes: 'Very active lifestyle. Needs sports-specific rehab program.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Wong',
      lastName: 'Kai Xin',
      email: 'kaixin.wong@gmail.com',
      phone: '+60 11-1111 2005',
      icNumber: '880620-14-3398',
      dateOfBirth: new Date('1988-06-20'),
      gender: 'Female',
      occupation: 'Marketing Manager',
      race: 'Chinese',
      maritalStatus: 'Married',
      bloodType: 'O-',
      allergies: 'Ibuprofen',
      referralSource: 'Google Search',
      addressLine1: '15, Persiaran KLCC',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50088',
      emergencyName: 'Wong Jun Wei',
      emergencyPhone: '+60 12-999 0005',
      emergencyRelation: 'Husband',
      medicalHistory: 'Prenatal care — 28 weeks pregnant. Sciatic pain on right side.',
      notes: 'Referred for Webster Technique. Prefers Dr. Aisha.',
      status: 'active',
      doctorIndex: 1,
    },
    {
      firstName: 'Siti',
      lastName: 'Nurhaliza',
      email: 'siti.nurhaliza@gmail.com',
      phone: '+60 11-1111 2006',
      icNumber: '950101-06-7788',
      dateOfBirth: new Date('1995-01-01'),
      gender: 'Female',
      occupation: 'Nurse',
      race: 'Malay',
      maritalStatus: 'Single',
      bloodType: 'A-',
      allergies: null,
      referralSource: 'Walk-in',
      addressLine1: '33, Jalan Tun Razak',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50400',
      emergencyName: 'Zainab binti Ali',
      emergencyPhone: '+60 12-999 0006',
      emergencyRelation: 'Sister',
      medicalHistory: 'Repetitive strain injury from patient handling. Wrist and shoulder pain.',
      notes: 'Shift worker — needs flexible appointment times.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Liew',
      lastName: 'Chun Hao',
      email: 'chunhao.liew@outlook.com',
      phone: '+60 11-1111 2007',
      icNumber: '700215-07-9901',
      dateOfBirth: new Date('1970-02-15'),
      gender: 'Male',
      occupation: 'Retired',
      race: 'Chinese',
      maritalStatus: 'Married',
      bloodType: 'B-',
      allergies: 'Aspirin',
      referralSource: 'Son recommended',
      addressLine1: '7, Jalan Bangsar',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '59200',
      emergencyName: 'Liew Jun Yang',
      emergencyPhone: '+60 12-999 0007',
      emergencyRelation: 'Son',
      medicalHistory: 'Degenerative disc disease. Osteoarthritis in cervical spine. Previous cervical fusion C5-C6.',
      notes: 'Requires gentle technique only. No manual manipulation of cervical spine.',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Muthu',
      lastName: 'Selvam',
      email: 'muthu.selvam@gmail.com',
      phone: '+60 11-1111 2008',
      icNumber: '830730-10-2234',
      dateOfBirth: new Date('1983-07-30'),
      gender: 'Male',
      occupation: 'Construction Foreman',
      race: 'Indian',
      maritalStatus: 'Married',
      bloodType: 'O+',
      allergies: null,
      referralSource: 'Colleague',
      addressLine1: '18, Jalan Klang Lama',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '58100',
      emergencyName: 'Lakshmi Selvam',
      emergencyPhone: '+60 12-999 0008',
      emergencyRelation: 'Wife',
      medicalHistory: 'Heavy lifting injuries. Chronic lumbar pain. Disc bulge L5-S1.',
      notes: 'Only available on weekends and after 5pm on weekdays.',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Nurul',
      lastName: 'Izzati',
      email: 'nurul.izzati@gmail.com',
      phone: '+60 11-1111 2009',
      icNumber: '000512-14-6677',
      dateOfBirth: new Date('2000-05-12'),
      gender: 'Female',
      occupation: 'University Student',
      race: 'Malay',
      maritalStatus: 'Single',
      bloodType: 'A+',
      allergies: null,
      referralSource: 'University health center',
      addressLine1: '5, Jalan Universiti',
      city: 'Petaling Jaya',
      state: 'Selangor',
      postcode: '46200',
      emergencyName: 'Roslan bin Yusof',
      emergencyPhone: '+60 12-999 0009',
      emergencyRelation: 'Father',
      medicalHistory: 'Poor posture from prolonged studying. Tension headaches.',
      notes: 'Student budget — consider shorter sessions. Very responsive to treatment.',
      status: 'active',
      doctorIndex: 1,
    },
    {
      firstName: 'David',
      lastName: 'Ong',
      email: 'david.ong@proton.me',
      phone: '+60 11-1111 2010',
      icNumber: '870923-10-1122',
      dateOfBirth: new Date('1987-09-23'),
      gender: 'Male',
      occupation: 'Lawyer',
      race: 'Chinese',
      maritalStatus: 'Divorced',
      bloodType: 'AB-',
      allergies: 'Codeine',
      referralSource: 'Google Search',
      addressLine1: '10, Jalan Sultan Ismail',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50250',
      emergencyName: 'Ong Mei Fong',
      emergencyPhone: '+60 12-999 0010',
      emergencyRelation: 'Mother',
      medicalHistory: 'Stress-related tension. TMJ dysfunction. Cervical spine subluxation.',
      notes: 'High-stress occupation. Benefits from full-spine adjustments.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Zainab',
      lastName: 'binti Osman',
      email: 'zainab.osman@gmail.com',
      phone: '+60 11-1111 2011',
      icNumber: '750818-02-4456',
      dateOfBirth: new Date('1975-08-18'),
      gender: 'Female',
      occupation: 'Business Owner',
      race: 'Malay',
      maritalStatus: 'Widowed',
      bloodType: 'B+',
      allergies: null,
      referralSource: 'Newspaper ad',
      addressLine1: '25, Jalan Damansara',
      city: 'Petaling Jaya',
      state: 'Selangor',
      postcode: '47400',
      emergencyName: 'Kamal bin Osman',
      emergencyPhone: '+60 12-999 0011',
      emergencyRelation: 'Son',
      medicalHistory: 'Post-menopausal osteopenia. Mild kyphosis. Lower back stiffness.',
      notes: 'VIP patient — very particular about punctuality. Prefers private treatment room.',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Lee',
      lastName: 'Jia Hui',
      email: 'jiahui.lee@gmail.com',
      phone: '+60 11-1111 2012',
      icNumber: '960304-14-8899',
      dateOfBirth: new Date('1996-03-04'),
      gender: 'Female',
      occupation: 'Graphic Designer',
      race: 'Chinese',
      maritalStatus: 'Single',
      bloodType: 'O+',
      allergies: null,
      referralSource: 'TikTok',
      addressLine1: '42, Jalan Imbi',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '55100',
      emergencyName: 'Lee Ah Kow',
      emergencyPhone: '+60 12-999 0012',
      emergencyRelation: 'Father',
      medicalHistory: 'Text neck syndrome. Mouse shoulder (right side). Carpal tunnel symptoms.',
      notes: 'Digital nomad — sometimes works from clinic lobby while waiting.',
      status: 'active',
      doctorIndex: 1,
    },
    {
      firstName: 'Arjun',
      lastName: 'Pillai',
      email: 'arjun.pillai@gmail.com',
      phone: '+60 11-1111 2013',
      icNumber: '810611-07-3345',
      dateOfBirth: new Date('1981-06-11'),
      gender: 'Male',
      occupation: 'Taxi Driver (e-hailing)',
      race: 'Indian',
      maritalStatus: 'Married',
      bloodType: 'A+',
      allergies: null,
      referralSource: 'Family member',
      addressLine1: '16, Jalan Sentul',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '51000',
      emergencyName: 'Devi Pillai',
      emergencyPhone: '+60 12-999 0013',
      emergencyRelation: 'Wife',
      medicalHistory: 'Prolonged sitting — sciatica. Hip flexor tightness. Lumbar disc protrusion.',
      notes: 'Irregular schedule due to e-hailing work. Prefers walk-in when available.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Hafiz',
      lastName: 'bin Abdullah',
      email: 'hafiz.abdullah@gmail.com',
      phone: '+60 11-1111 2014',
      icNumber: '980220-14-5501',
      dateOfBirth: new Date('1998-02-20'),
      gender: 'Male',
      occupation: 'Badminton Coach',
      race: 'Malay',
      maritalStatus: 'Single',
      bloodType: 'O+',
      allergies: null,
      referralSource: 'Sports club',
      addressLine1: '9, Jalan Bukit Kiara',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '60000',
      emergencyName: 'Abdullah bin Hashim',
      emergencyPhone: '+60 12-999 0014',
      emergencyRelation: 'Father',
      medicalHistory: 'Shoulder impingement (right). Ankle sprain history. Sports performance optimization.',
      notes: 'Athlete — interested in performance chiropractic, not just pain relief.',
      status: 'active',
      doctorIndex: 0,
    },
    {
      firstName: 'Chong',
      lastName: 'Siew Mei',
      email: null,
      phone: '+60 11-1111 2015',
      icNumber: '650430-08-2278',
      dateOfBirth: new Date('1965-04-30'),
      gender: 'Female',
      occupation: 'Homemaker',
      race: 'Chinese',
      maritalStatus: 'Married',
      bloodType: 'B+',
      allergies: 'Shellfish (dietary only)',
      referralSource: 'Daughter brought her',
      addressLine1: '3, Jalan Cheras',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '56100',
      emergencyName: 'Chong Mei Yi',
      emergencyPhone: '+60 12-999 0015',
      emergencyRelation: 'Daughter',
      medicalHistory: 'Frozen shoulder (left). Cervical spondylosis. Hypertension (controlled with medication).',
      notes: 'Elderly patient. Daughter usually accompanies. Speaks limited English — prefers Mandarin.',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Sarah',
      lastName: 'binti Yusof',
      email: 'sarah.yusof@gmail.com',
      phone: '+60 11-1111 2016',
      icNumber: '911115-14-9902',
      dateOfBirth: new Date('1991-11-15'),
      gender: 'Female',
      occupation: 'Flight Attendant',
      race: 'Malay',
      maritalStatus: 'Married',
      bloodType: 'A+',
      allergies: null,
      referralSource: 'Crew member recommendation',
      addressLine1: '28, Jalan Kia Peng',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50450',
      emergencyName: 'Yusof bin Hamid',
      emergencyPhone: '+60 12-999 0016',
      emergencyRelation: 'Husband',
      medicalHistory: 'Upper back pain from luggage handling. Jet lag related tension. Poor sleep posture.',
      notes: 'Travels frequently — books appointments in batches when in KL.',
      status: 'inactive',
      doctorIndex: 1,
    },
    {
      firstName: 'Ganesh',
      lastName: 'Rao',
      email: 'ganesh.rao@gmail.com',
      phone: '+60 11-1111 2017',
      icNumber: '720805-10-1190',
      dateOfBirth: new Date('1972-08-05'),
      gender: 'Male',
      occupation: 'Chef',
      race: 'Indian',
      maritalStatus: 'Married',
      bloodType: 'O-',
      allergies: null,
      referralSource: 'Walk-in',
      addressLine1: '11, Jalan Alor',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postcode: '50200',
      emergencyName: 'Meena Rao',
      emergencyPhone: '+60 12-999 0017',
      emergencyRelation: 'Wife',
      medicalHistory: 'Standing for long hours. Plantar fasciitis. Lower back pain with radiating leg pain.',
      notes: 'Works late nights — only available before 11am or on Mondays (restaurant closed).',
      status: 'active',
      doctorIndex: 2,
    },
    {
      firstName: 'Amir',
      lastName: 'bin Zakaria',
      email: 'amir.zakaria@gmail.com',
      phone: '+60 11-1111 2018',
      icNumber: '030901-14-3344',
      dateOfBirth: new Date('2003-09-01'),
      gender: 'Male',
      occupation: 'College Student (IT)',
      race: 'Malay',
      maritalStatus: 'Single',
      bloodType: 'AB+',
      allergies: null,
      referralSource: 'Mother is existing patient',
      addressLine1: '6, Jalan Gasing',
      city: 'Petaling Jaya',
      state: 'Selangor',
      postcode: '46000',
      emergencyName: 'Zainab binti Osman',
      emergencyPhone: '+60 12-999 0011',
      emergencyRelation: 'Mother',
      medicalHistory: 'Gaming posture issues. Thoracic kyphosis. Neck pain.',
      notes: 'Son of patient Zainab. Young and responsive to postural correction exercises.',
      status: 'active',
      doctorIndex: 1,
    },
  ]

  let patientCount = 0
  for (const p of patientsData) {
    const doctor = allDoctors[p.doctorIndex]

    await prisma.patient.upsert({
      where: {
        id: `seed-patient-${String(patientCount + 1).padStart(3, '0')}`,
      },
      update: {},
      create: {
        id: `seed-patient-${String(patientCount + 1).padStart(3, '0')}`,
        firstName: p.firstName,
        lastName: p.lastName,
        email: p.email,
        phone: p.phone,
        icNumber: p.icNumber,
        dateOfBirth: p.dateOfBirth,
        gender: p.gender,
        occupation: p.occupation,
        race: p.race,
        maritalStatus: p.maritalStatus,
        bloodType: p.bloodType,
        allergies: p.allergies,
        referralSource: p.referralSource,
        addressLine1: p.addressLine1,
        addressLine2: (p as Record<string, unknown>).addressLine2 as string | undefined,
        city: p.city,
        state: p.state,
        postcode: p.postcode,
        country: 'Malaysia',
        emergencyName: p.emergencyName,
        emergencyPhone: p.emergencyPhone,
        emergencyRelation: p.emergencyRelation,
        medicalHistory: p.medicalHistory,
        notes: p.notes,
        status: p.status,
        branchId: branch.id,
        doctorId: doctor.id,
      },
    })

    patientCount++
  }

  console.log(`Seeded ${patientCount} patients`)

  // ─── Visits (recent history for some patients) ───
  const now = new Date()
  const visitData = [
    { patientIdx: 0, daysAgo: 3, subjective: 'Lower back pain improved since last visit. Pain 4/10 from 7/10.', objective: 'Lumbar ROM improved. L4-L5 still restricted on palpation.', assessment: 'Improving lumbar subluxation complex. Good response to Gonstead adjustments.', plan: 'Continue bi-weekly adjustments. Add core stability exercises.' },
    { patientIdx: 0, daysAgo: 17, subjective: 'Acute lower back pain after prolonged sitting at work. Pain 7/10.', objective: 'Antalgic posture. Reduced lumbar lordosis. Positive Kemp test left.', assessment: 'Lumbar subluxation L4-L5 with disc involvement.', plan: 'Gonstead adjustment L4-L5. Ice 15min post-adjustment. Ergonomic desk review.' },
    { patientIdx: 2, daysAgo: 1, subjective: 'Maintenance visit. Feeling good overall. Mild stiffness in thoracic region.', objective: 'T5-T7 fixation on palpation. Scoliotic curve stable.', assessment: 'Stable thoracic subluxation pattern. Scoliosis maintained.', plan: 'Thoracic adjustment T5-T7. Continue 2-week maintenance schedule.' },
    { patientIdx: 2, daysAgo: 15, subjective: 'Thoracic stiffness after long weekend of marking exam papers.', objective: 'Increased T5-T7 fixation. Mild paraspinal muscle spasm.', assessment: 'Thoracic subluxation exacerbation from sustained flexion posture.', plan: 'Thompson technique adjustment. Postural awareness education.' },
    { patientIdx: 3, daysAgo: 5, subjective: 'Shoulder pain reduced. Disc symptoms stable. Training at 70% intensity.', objective: 'Right shoulder ROM near full. Positive SLR at 60° (improved from 45°).', assessment: 'Improving L4-L5 disc herniation. Shoulder impingement resolving.', plan: 'Gradual return to full training. Adjustment focus on lumbar and shoulder girdle.' },
    { patientIdx: 6, daysAgo: 7, subjective: 'Neck stiffness improved. No radiating arm symptoms this week.', objective: 'Cervical ROM restricted in rotation. C5-C6 fusion stable.', assessment: 'Stable post-surgical cervical spine. Compensatory patterns above and below fusion.', plan: 'Gentle Activator adjustment C3-C4 and C7-T1. Avoid manual cervical manipulation.' },
    { patientIdx: 9, daysAgo: 10, subjective: 'Jaw clicking reduced. Neck tension still present after long court cases.', objective: 'TMJ dysfunction right side. Cervical subluxation C1-C2.', assessment: 'TMJ-cervical complex dysfunction. Stress-related muscle tension.', plan: 'Atlas adjustment. TMJ release technique. Stress management discussion.' },
    { patientIdx: 4, daysAgo: 2, subjective: 'Sciatic pain much better. Baby very active. 30 weeks now.', objective: 'Webster technique assessment positive. SI joint dysfunction right.', assessment: 'Pregnancy-related SI joint dysfunction. Responding well to Webster technique.', plan: 'Continue Webster technique weekly until delivery. Pelvic support belt recommended.' },
  ]

  let visitCount = 0
  for (const v of visitData) {
    const patientId = `seed-patient-${String(v.patientIdx + 1).padStart(3, '0')}`
    const patient = patientsData[v.patientIdx]
    const doctor = allDoctors[patient.doctorIndex]
    const visitDate = new Date(now)
    visitDate.setDate(visitDate.getDate() - v.daysAgo)

    await prisma.visit.create({
      data: {
        visitDate,
        subjective: v.subjective,
        objective: v.objective,
        assessment: v.assessment,
        plan: v.plan,
        patientId,
        doctorId: doctor.id,
      },
    })
    visitCount++
  }

  console.log(`Seeded ${visitCount} visits`)

  // ─── Appointments (upcoming + today) ───
  const appointmentData = [
    { patientIdx: 0, daysFromNow: 0, hour: 10, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 4, daysFromNow: 0, hour: 11, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 8, daysFromNow: 0, hour: 14, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 2, daysFromNow: 0, hour: 15, duration: 30, status: 'CHECKED_IN' as const },
    { patientIdx: 12, daysFromNow: 1, hour: 9, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 3, daysFromNow: 1, hour: 10, duration: 45, status: 'SCHEDULED' as const },
    { patientIdx: 6, daysFromNow: 2, hour: 9, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 10, daysFromNow: 2, hour: 11, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 9, daysFromNow: 3, hour: 14, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 1, daysFromNow: 4, hour: 10, duration: 30, status: 'SCHEDULED' as const },
    { patientIdx: 7, daysFromNow: 5, hour: 16, duration: 45, status: 'SCHEDULED' as const },
    { patientIdx: 13, daysFromNow: 7, hour: 9, duration: 30, status: 'SCHEDULED' as const },
  ]

  let apptCount = 0
  for (const a of appointmentData) {
    const patientId = `seed-patient-${String(a.patientIdx + 1).padStart(3, '0')}`
    const patient = patientsData[a.patientIdx]
    const doctor = allDoctors[patient.doctorIndex]

    const dateTime = new Date(now)
    dateTime.setDate(dateTime.getDate() + a.daysFromNow)
    dateTime.setHours(a.hour, 0, 0, 0)

    await prisma.appointment.create({
      data: {
        dateTime,
        duration: a.duration,
        status: a.status,
        patientId,
        branchId: branch.id,
        doctorId: doctor.id,
      },
    })
    apptCount++
  }

  console.log(`Seeded ${apptCount} appointments`)

  console.log('\n✓ Seed complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
